version: "3"

name: "ddms"

services:
  db:
    image: mysql:latest
    container_name: ddms-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ddms
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - ddms-net
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./mysql:/var/lib/mysql

  backend:
    build: ./backend
    container_name: ddms-api
    restart: always
    ports:
      - "5000:5000"
    networks:
      ddms-net:
        ipv4_address: 172.16.238.10
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: app
      DB_PASSWORD: password
      DB_NAME: ddms
      # REPLACE THIS IP WITH THE STATIC IP OF THE HOST SERVER
      FRONTEND_IP: 192.168.1.7
      BACKEND_PORT: 5000
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: ddms-app
    restart: always
    networks:
      ddms-net:
        ipv4_address: 172.16.238.20
    ports:
      - "3000:3000"
    environment:
      #CHANGE THIS IP IN FRONTEND->DOCKERFILE
      BACKEND_HOST: 172.16.238.10
      API_PORT: 5000
    depends_on:
      - backend

networks:
  ddms-net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
