const Excel = require("exceljs");
const { User } = require("../models/user");
const { userUploadSchema } = require("../schemas");
const controller = require("../controllers/user");
const { sendMail } = require("../utils/email");

const extractUsers = async (filename) => {
  const workbook = new Excel.Workbook();
  errorValues = [];
  successCount = 0;
  lastprocessed = 0;
  await workbook.xlsx.readFile(filename);
  workbook.eachSheet(async (worksheet, sheetID) => {
    worksheet.eachRow(async (row, rowNumber) => {
      lastprocessed++;
      if (rowNumber > 1) {
        let user = {
          email: row.values[3],
          fullname: row.values[2],
          role: row.values[4],
        };
        const { error } = userUploadSchema.validate(user);
        if (error) {
          user.errmsg = error.details[0].message;
          errorValues.push(user);
        } else {
          successCount++;
          let password = controller.genPassword();
          console.log(user.email, password);
          let result = controller.register(user, password);
          if (result) {
            successCount--;
          } else {
            sendMail(
              user.email,
              "Account Details",
              `Hello ${user.fullname},\n Your password is ${password}, use it to login and fill in the required student details \n Thank You\n NOTE: This is email is generated by DDMS`
            );
          }
        }
      }
    });
  });
  if (errorValues.length == 0) {
    return {
      result: "SUCCESS",
      msg: `${successCount} users added out of ${lastprocessed - 1}`,
    };
  } else {
    return {
      result: "FAILURE",
      msg: `${successCount} users added out of ${lastprocessed - 1}`,
      errdata: errorValues,
    };
  }
};
module.exports = { extractUsers };
